name: 🚀 Feature
description: Suggest an idea for this project 💡
title: 'Feature: '
labels: [👀 needs triage, 💡 feature]
body:
  - type: dropdown
    attributes:
      multiple: false
      label: Type of feature
      description: Select the type of feature.
      options:
        - '🍕 Feature'
        - '📝 Documentation'
        - '🎨 Style'
        - '🧑‍💻 Refactor'
        - '🔥 Performance'
        - '✅ Test'
        - '🤖 Build'
        - '🔁 CI'
        - '📦 Chore'
        - '⏩ Revert'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: Describe your proposal.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Tasks
      description: Create your own tasks by checking the boxes or adding new tasks.
      options:
        - 'Task 1'
        - 'Task 2'
        - 'Task 3'
    validations:
      required: true
