import { User } from '@/types/common.types';
import { Post } from '@/features/home/types/types';

export const userData: User[] = [
  {
    id: 1,
    userName: 'johndoe82',
    email: 'johndoe82@example.com',
    password: 'password123',
    avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
    displayName: 'John Doe',
    isVerified: true,
  },
  {
    id: 2,
    userName: 'janesmith74',
    email: 'janesmith74@example.com',
    password: 'securePassword',
    avatar: 'https://randomuser.me/api/portraits/women/2.jpg',
    displayName: 'Jane Smith',
    isVerified: false,
  },
  {
    id: 3,
    userName: 'alicej99',
    email: 'alicej99@example.com',
    password: 'mySecretPassword',
    avatar: 'https://randomuser.me/api/portraits/women/3.jpg',
    displayName: 'Alice Johnson',
    isVerified: true,
  },
  {
    id: 4,
    userName: 'rbrown87',
    email: 'rbrown87@example.com',
    password: 'brownie123',
    avatar: 'https://randomuser.me/api/portraits/men/4.jpg',
    displayName: 'Robert Brown',
    isVerified: false,
  },
  {
    id: 5,
    userName: 'emilydavis',
    email: 'emily.davis@example.com',
    password: 'ilovecoding',
    avatar: 'https://randomuser.me/api/portraits/women/5.jpg',
    displayName: 'Emily Davis',
    isVerified: true,
  },
  {
    id: 6,
    userName: 'michaelwilson',
    email: 'michael.wilson@example.com',
    password: 'mike1234',
    avatar: 'https://randomuser.me/api/portraits/men/6.jpg',
    displayName: 'Michael Wilson',
    isVerified: false,
  },
  {
    id: 7,
    userName: 'sarahmiller',
    email: 'sarah.miller@example.com',
    password: 'sarahsPass',
    avatar: 'https://randomuser.me/api/portraits/women/7.jpg',
    displayName: 'Sarah Miller',
    isVerified: true,
  },
  {
    id: 8,
    userName: 'davidlee88',
    email: 'david.lee@example.com',
    password: 'dlee789',
    avatar: 'https://randomuser.me/api/portraits/men/8.jpg',
    displayName: 'David Lee',
    isVerified: false,
  },
  {
    id: 9,
    userName: 'oliviaharris',
    email: 'olivia.harris@example.com',
    password: '12345678',
    avatar: 'https://randomuser.me/api/portraits/women/9.jpg',
    displayName: 'Olivia Harris',
    isVerified: true,
  },
];

const dummyUser = (): User =>
  userData[Math.floor(Math.random() * userData.length)];

export const dummyPostData: Post[] = [
  {
    _id: '1',
    author: dummyUser().displayName,
    content: 'This is the first post content.',
    tags: ['Tag1', 'Tag2'],
    authorSlug: dummyUser().userName,
    length: 30,
    dateAdded: '2023-11-07',
    dateModified: '2023-11-07',
    image: 'https://picsum.photos/400/200?random=1',
    user: dummyUser(),
  },
  {
    _id: '2',
    author: dummyUser().displayName,
    content: 'Another post for testing purposes.',
    tags: ['Tag3', 'Tag4'],
    authorSlug: dummyUser().userName,
    length: 42,
    dateAdded: '2023-11-07',
    dateModified: '2023-11-07',
    image: 'https://picsum.photos/400/200?random=2',
    user: dummyUser(),
  },
  {
    _id: '3',
    author: dummyUser().displayName,
    content: 'Lorem ipsum dolor sit amet.',
    tags: ['Tag5', 'Tag6'],
    authorSlug: dummyUser().userName,
    length: 60,
    dateAdded: '2023-11-07',
    dateModified: '2023-11-07',
    image: 'https://picsum.photos/400/200?random=3',
    user: dummyUser(),
  },
  {
    _id: '4',
    author: dummyUser().displayName,
    content: 'Yet another post with some content.',
    tags: ['Tag7', 'Tag8'],
    authorSlug: dummyUser().userName,
    length: 55,
    dateAdded: '2023-11-07',
    dateModified: '2023-11-07',
    image: 'https://picsum.photos/400/200?random=4',
    user: dummyUser(),
  },
  {
    _id: '5',
    author: dummyUser().displayName,
    content: 'Fifth post in the list.',
    tags: ['Tag9', 'Tag10'],
    authorSlug: dummyUser().userName,
    length: 35,
    dateAdded: '2023-11-07',
    dateModified: '2023-11-07',
    image: 'https://picsum.photos/400/200?random=5',
    user: dummyUser(),
  },
  {
    _id: '6',
    author: dummyUser().displayName,
    content: 'This post has a different content.',
    tags: ['Tag11', 'Tag12'],
    authorSlug: dummyUser().userName,
    length: 48,
    dateAdded: '2023-11-07',
    dateModified: '2023-11-07',
    image: 'https://picsum.photos/400/200?random=6',
    user: dummyUser(),
  },
  {
    _id: '7',
    author: dummyUser().displayName,
    content: 'Seventh post content goes here.',
    tags: ['Tag13', 'Tag14'],
    authorSlug: dummyUser().userName,
    length: 38,
    dateAdded: '2023-11-07',
    dateModified: '2023-11-07',
    image: 'https://picsum.photos/400/200?random=7',
    user: dummyUser(),
  },
  {
    _id: '8',
    author: dummyUser().displayName,
    content: 'Eighth post for testing.',
    tags: ['Tag15', 'Tag16'],
    authorSlug: dummyUser().userName,
    length: 46,
    dateAdded: '2023-11-07',
    dateModified: '2023-11-07',
    image: 'https://picsum.photos/400/200?random=8',
    user: dummyUser(),
  },
  {
    _id: '9',
    author: dummyUser().displayName,
    content: 'Ninth post with some content.',
    tags: ['Tag17', 'Tag18'],
    authorSlug: dummyUser().userName,
    length: 52,
    dateAdded: '2023-11-07',
    dateModified: '2023-11-07',
    image: 'https://picsum.photos/400/200?random=9',
    user: dummyUser(),
  },
  {
    _id: '10',
    author: dummyUser().displayName,
    content: 'Tenth post in the list.',
    tags: ['Tag19', 'Tag20'],
    authorSlug: dummyUser().userName,
    length: 44,
    dateAdded: '2023-11-07',
    dateModified: '2023-11-07',
    image: 'https://picsum.photos/400/200?random=10',
    user: dummyUser(),
  },
];
