import { User } from '@/types/common.types';
import { Post } from '@/types/home.type';

// postData.ts or at the top of your Feed.tsx
export const postData: Post[] = [
  {
    _id: '1',
    author: 'John Doe',
    content: 'This is the first post content.',
    tags: ['Tag1', 'Tag2'],
    authorSlug: 'john-doe',
    length: 30,
    dateAdded: '2023-11-07',
    dateModified: '2023-11-07',
  },
  {
    _id: '2',
    author: 'Jane Smith',
    content: 'Another post for testing purposes.',
    tags: ['Tag3', 'Tag4'],
    authorSlug: 'jane-smith',
    length: 42,
    dateAdded: '2023-11-07',
    dateModified: '2023-11-07',
  },
  {
    _id: '3',
    author: 'Alice Johnson',
    content: 'Lorem ipsum dolor sit amet.',
    tags: ['Tag5', 'Tag6'],
    authorSlug: 'alice-johnson',
    length: 60,
    dateAdded: '2023-11-07',
    dateModified: '2023-11-07',
  },
  {
    _id: '4',
    author: 'Bob Brown',
    content: 'Yet another post with some content.',
    tags: ['Tag7', 'Tag8'],
    authorSlug: 'bob-brown',
    length: 55,
    dateAdded: '2023-11-07',
    dateModified: '2023-11-07',
  },
  {
    _id: '5',
    author: 'Eve Taylor',
    content: 'Fifth post in the list.',
    tags: ['Tag9', 'Tag10'],
    authorSlug: 'eve-taylor',
    length: 35,
    dateAdded: '2023-11-07',
    dateModified: '2023-11-07',
  },
  {
    _id: '6',
    author: 'Michael Clark',
    content: 'This post has a different content.',
    tags: ['Tag11', 'Tag12'],
    authorSlug: 'michael-clark',
    length: 48,
    dateAdded: '2023-11-07',
    dateModified: '2023-11-07',
  },
  {
    _id: '7',
    author: 'Lucy White',
    content: 'Seventh post content goes here.',
    tags: ['Tag13', 'Tag14'],
    authorSlug: 'lucy-white',
    length: 38,
    dateAdded: '2023-11-07',
    dateModified: '2023-11-07',
  },
  {
    _id: '8',
    author: 'David King',
    content: 'Eighth post for testing.',
    tags: ['Tag15', 'Tag16'],
    authorSlug: 'david-king',
    length: 46,
    dateAdded: '2023-11-07',
    dateModified: '2023-11-07',
  },
  {
    _id: '9',
    author: 'Sarah Turner',
    content: 'Ninth post with some content.',
    tags: ['Tag17', 'Tag18'],
    authorSlug: 'sarah-turner',
    length: 52,
    dateAdded: '2023-11-07',
    dateModified: '2023-11-07',
  },
  {
    _id: '10',
    author: 'Daniel Lewis',
    content: 'Tenth post in the list.',
    tags: ['Tag19', 'Tag20'],
    authorSlug: 'daniel-lewis',
    length: 44,
    dateAdded: '2023-11-07',
    dateModified: '2023-11-07',
  },
];
export const dummyUsers: User[] = [
  {
    id: 1,
    name: 'John Doe',
    email: 'john.doe@example.com',
    password: 'password123',
  },
  {
    id: 2,
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    password: 'securePassword',
  },
  {
    id: 3,
    name: 'Alice Johnson',
    email: 'alice.johnson@example.com',
    password: 'mySecretPassword',
  },
  {
    id: 4,
    name: 'Robert Brown',
    email: 'robert.brown@example.com',
    password: 'brownie123',
  },
  {
    id: 5,
    name: 'Emily Davis',
    email: 'emily.davis@example.com',
    password: 'ilovecoding',
  },
  {
    id: 6,
    name: 'Michael Wilson',
    email: 'michael.wilson@example.com',
    password: 'mike1234',
  },
  {
    id: 7,
    name: 'Sarah Miller',
    email: 'sarah.miller@example.com',
    password: 'sarahsPass',
  },
  {
    id: 8,
    name: 'David Lee',
    email: 'david.lee@example.com',
    password: 'dlee789',
  },
  {
    id: 9,
    name: 'Olivia Harris',
    email: 'olivia.harris@example.com',
    password: '12345678',
  },
];
