import { User } from '@/types/common.types';
import { Post } from '@/types/home.type';

// postData.ts or at the top of your Feed.tsx
export const postData: Post[] = [
  {
    id: 1,
    displayName: 'User One',
    username: '@user1',
    verified: true,
    text: 'This is the first post',
    image: 'https://picsum.photos/400/200?random=1',
    avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
  },
  {
    id: 2,
    displayName: 'User Two',
    username: '@user2',
    verified: false,
    text: 'This is the second post',
    image: 'https://picsum.photos/400/200?random=2',
    avatar: 'https://randomuser.me/api/portraits/men/2.jpg',
  },
  {
    id: 3,
    displayName: 'User Three',
    username: '@user3',
    verified: true,
    text: 'This is the third post',
    image: 'https://picsum.photos/400/200?random=3',
    avatar: 'https://randomuser.me/api/portraits/women/3.jpg',
  },
  {
    id: 4,
    displayName: 'User Four',
    username: '@user4',
    verified: false,
    text: 'This is the fourth post',
    image: 'https://picsum.photos/400/200?random=4',
    avatar: 'https://randomuser.me/api/portraits/men/4.jpg',
  },
  {
    id: 5,
    displayName: 'User Five',
    username: '@user5',
    verified: true,
    text: 'This is the fifth post',
    image: 'https://picsum.photos/400/200?random=5',
    avatar: 'https://randomuser.me/api/portraits/women/5.jpg',
  },
  {
    id: 6,
    displayName: 'User Six',
    username: '@user6',
    verified: false,
    text: 'This is the sixth post',
    image: 'https://picsum.photos/400/200?random=6',
    avatar: 'https://randomuser.me/api/portraits/men/6.jpg',
  },
  {
    id: 7,
    displayName: 'User Seven',
    username: '@user7',
    verified: true,
    text: 'This is the seventh post',
    image: 'https://picsum.photos/400/200?random=7',
    avatar: 'https://randomuser.me/api/portraits/women/7.jpg',
  },
  {
    id: 8,
    displayName: 'User Eight',
    username: '@user8',
    verified: false,
    text: 'This is the eighth post',
    image: 'https://picsum.photos/400/200?random=8',
    avatar: 'https://randomuser.me/api/portraits/men/8.jpg',
  },
  {
    id: 9,
    displayName: 'User Nine',
    username: '@user9',
    verified: true,
    text: 'This is the ninth post',
    image: 'https://picsum.photos/400/200?random=9',
    avatar: 'https://randomuser.me/api/portraits/women/9.jpg',
  },
  {
    id: 10,
    displayName: 'User Ten',
    username: '@user10',
    verified: false,
    text: 'This is the tenth post',
    image: 'https://picsum.photos/400/200?random=10',
    avatar: 'https://randomuser.me/api/portraits/women/10.jpg',
  },
];
export const dummyUsers: User[] = [
  {
    id: 1,
    name: 'John Doe',
    email: 'john.doe@example.com',
    password: 'password123',
  },
  {
    id: 2,
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    password: 'securePassword',
  },
  {
    id: 3,
    name: 'Alice Johnson',
    email: 'alice.johnson@example.com',
    password: 'mySecretPassword',
  },
  {
    id: 4,
    name: 'Robert Brown',
    email: 'robert.brown@example.com',
    password: 'brownie123',
  },
  {
    id: 5,
    name: 'Emily Davis',
    email: 'emily.davis@example.com',
    password: 'ilovecoding',
  },
  {
    id: 6,
    name: 'Michael Wilson',
    email: 'michael.wilson@example.com',
    password: 'mike1234',
  },
  {
    id: 7,
    name: 'Sarah Miller',
    email: 'sarah.miller@example.com',
    password: 'sarahsPass',
  },
  {
    id: 8,
    name: 'David Lee',
    email: 'david.lee@example.com',
    password: 'dlee789',
  },
  {
    id: 9,
    name: 'Olivia Harris',
    email: 'olivia.harris@example.com',
    password: '12345678',
  },
];
